# =1. IMPORTANT: these variables are needed for the program to work
# 2. They will require registering an app with Genius and Spotify
# 3. To use this program, replace the phoney values with the real ones and rename this file to secret.py

# Genius Client Access Token
# Can be generated by registering a client with Genius
access_token = 'ex@ample-va@lue'

# Spotify Client Id + Secret
# Can be generated by registering a client with Spotify
client_id = 'ex@ample-va@lue'
client_secret = 'ex@ample-va@lue'
